CREATE TABLE BOARD(
	IDX INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	WRITER VARCHAR(30) NOT NULL,
	INDATE DATETIME DEFAULT NOW(),
	COUNT INT DEFAULT 0,
	PRIMARY KEY(IDX)
);

INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('100억 부자 유병재 vs 100억 빚 차은우','차은우!','???');
INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('1000억 부자 유병재 vs 100억 빚 차은우','차은우!','???');
INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('1조 부자 유병재 vs 100억 빚 차은우','차은우!','???');
INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('10조 부자 유병재 vs 100억 빚 차은우','차은우!','???');
INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('100조 부자 유병재 vs 100억 빚 차은우','차은우!','???');

SELECT * FROM BOARD;
















